# -*- coding: utf-8 -*-
"""BrentProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KGsNdAZPpcto2bKKdKdnt0lHXjomNns7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import warnings
import random
import os
from pathlib import Path

from scipy.stats import skew, kurtosis
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import pywt
import xgboost as xgb
import optuna

warnings.filterwarnings("ignore")
optuna.logging.set_verbosity(optuna.logging.WARNING)

# ── Random Seed — Tekrarlanabilirlik ────────────────────────
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)

print(f"✓ Kütüphaneler yüklendi, random seed sabitlendi: {SEED}")

# ============================================================
# VERİ OKUMA
# ============================================================
# Repo kökünden bağımsız çalışsın diye path'ler bu dosyanın konumuna göre
# kuruluyor (diğer run_*.py script'leriyle aynı yaklaşım):
#   .../work/brentproject.py -> ROOT = .../ (repo kökü)
ROOT = Path(__file__).resolve().parents[1]
WORK = ROOT / "work"
DATA_PATH = WORK / "veriseti.xlsx"

df = pd.read_excel(DATA_PATH, sheet_name="data (1)")
df.columns = df.columns.str.strip()
df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values("Date").set_index("Date")

COLS = ["Brent_Petrol", "OVX", "GPRD", "GPRD_THREAT"]
for col in COLS:
    df[col] = pd.to_numeric(df[col], errors="coerce")
df.dropna(subset=COLS, inplace=True)

print(f"\n✓ Veri yüklendi")
print(f"  Satır sayısı  : {len(df)}")
print(f"  Tarih aralığı : {df.index.min().date()} → {df.index.max().date()}")
print(f"\n{df[COLS].describe().round(2)}")

COLS   = ["Brent_Petrol", "OVX", "GPRD", "GPRD_THREAT"]
LABELS = ["Brent Petrol (USD/varil)", "OVX — Petrol Volatilite Endeksi",
          "GPRD — Jeopolitik Risk", "GPRD Threat — Tehdit Bileşeni"]

COLORS = ["#1f77b4", "#2ca02c", "#ff7f0e", "#d62728"]

def style_ax(ax):
    ax.set_facecolor("white")
    ax.tick_params(colors="black", labelsize=8)
    for sp in ax.spines.values():
        sp.set_edgecolor("#888888")
    ax.grid(True, color="#dddddd", lw=0.6, alpha=0.8)

# ── 2.1 Temel İstatistikler ──────────────────────────────────
# Ortalama, medyan, std ve min/max değerleri karşılaştırıyoruz.
# Ortalama ≈ medyan ise dağılım simetriktir.
# Brent için büyük fark varsa bimodal yapı vardır (iki farklı fiyat rejimi).

print("=" * 60)
print("  2.1 — Temel İstatistikler")
print("=" * 60)
print(df[COLS].describe().round(2).to_string())

print("\n  Ek istatistikler:")
print(f"  {'Değişken':<20} {'Çarpıklık':>10}  {'Kurtosis':>10}")
print(f"  {'-'*44}")
for col in COLS:
    s = skew(df[col].dropna())
    k = kurtosis(df[col].dropna())
    print(f"  {col:<20} {s:>10.3f}  {k:>10.3f}")

# NOT — Çarpıklık > 1 veya < -1 → dağılım belirgin asimetrik
#        Kurtosis > 3 → kalın kuyruk, aşırı değer riski yüksek

# ── 2.2 Zaman Serisi Grafikleri ─────────────────────────────
# Dört değişkenin 2014-2024 arası seyri.
# Kriz dönemleri kırmızı kesik çizgi ile işaretleniyor.

fig, axes = plt.subplots(4, 1, figsize=(16, 14), sharex=True)
fig.patch.set_facecolor("white")

events = {
    "Covid\n(Nis 2020)" : "2020-04-01",
    "Ukrayna\n(Şub 2022)": "2022-02-24",
}

for i, (col, label, color) in enumerate(zip(COLS, LABELS, COLORS)):
    ax = axes[i]
    style_ax(ax)
    ax.plot(df.index, df[col], color=color, lw=1.1, alpha=0.95)
    ax.fill_between(df.index, df[col], df[col].min(), color=color, alpha=0.10)

    for event_label, event_date in events.items():
        ax.axvline(pd.Timestamp(event_date), color="black", lw=1.3, ls="--", alpha=0.8)
        ax.text(pd.Timestamp(event_date), ax.get_ylim()[1] * 0.92,
                event_label, color="black", fontsize=7, ha="center", va="top")

    ax.set_ylabel(label, color="black", fontsize=9)
    ax.tick_params(colors="black")

axes[-1].xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
axes[-1].xaxis.set_major_locator(mdates.YearLocator())
fig.suptitle("Değişkenlerin Zaman İçindeki Seyri (2014–2024)",
             fontsize=14, fontweight="bold", color="black")
plt.tight_layout()
plt.savefig("eda_timeseries.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()

# ── 2.3 Dağılım Histogramları (2×2) ─────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(14, 9))
fig.patch.set_facecolor("white")
axes = axes.flatten()

for i, (col, label, color) in enumerate(zip(COLS, LABELS, COLORS)):
    ax = axes[i]
    style_ax(ax)

    vals = df[col].dropna().values
    ax.hist(vals, bins=60, color=color, alpha=0.75, edgecolor="white", linewidth=0.3)



    ax.set_title(label, fontsize=11, fontweight="bold", color="black", pad=8)
    ax.set_xlabel("Değer", color="black", fontsize=9)
    ax.set_ylabel("Frekans", color="black", fontsize=9)

    info = f"Çarpıklık: {skew(vals):.2f}  Kurtosis: {kurtosis(vals):.2f}  Std: {vals.std():.2f}"
    ax.text(0.02, 0.96, info, transform=ax.transAxes, fontsize=7.5,
            color="black", va="top", fontfamily="monospace",
            bbox=dict(boxstyle="round,pad=0.3", facecolor="#f0f0f0", edgecolor="#cccccc"))
    ax.legend(fontsize=8, facecolor="white", edgecolor="#cccccc", labelcolor="black")

fig.suptitle("Değişken Dağılımları — Ham Veri", fontsize=13, fontweight="bold", color="black")
plt.tight_layout()
plt.savefig("eda_histograms.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()

# ── 2.4 Otokorelasyon Analizi (ACF & PACF) ──────────────────
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.stattools import acf, pacf

LAGS = 40
fig, axes = plt.subplots(len(COLS), 2, figsize=(16, 14))
fig.patch.set_facecolor("white")

for i, (col, color) in enumerate(zip(COLS, COLORS)):
    series = df[col].dropna()

    ax_acf = axes[i, 0]
    style_ax(ax_acf)
    acf_vals, _ = acf(series, nlags=LAGS, alpha=0.05)
    ax_acf.bar(range(len(acf_vals)), acf_vals, color=color, alpha=0.8, width=0.4)
    ax_acf.axhline( 1.96/np.sqrt(len(series)), color="black", lw=1.0, ls="--", alpha=0.8)
    ax_acf.axhline(-1.96/np.sqrt(len(series)), color="black", lw=1.0, ls="--", alpha=0.8)
    ax_acf.set_title(f"ACF — {col}", fontsize=10, fontweight="bold", color="black")
    ax_acf.set_ylim(-0.3, 1.05)

    ax_pacf = axes[i, 1]
    style_ax(ax_pacf)
    pacf_vals, _ = pacf(series, nlags=min(LAGS, len(series)//2 - 1), alpha=0.05)
    ax_pacf.bar(range(len(pacf_vals)), pacf_vals, color=color, alpha=0.8, width=0.4)
    ax_pacf.axhline( 1.96/np.sqrt(len(series)), color="black", lw=1.0, ls="--", alpha=0.8)
    ax_pacf.axhline(-1.96/np.sqrt(len(series)), color="black", lw=1.0, ls="--", alpha=0.8)
    ax_pacf.set_title(f"PACF — {col}", fontsize=10, fontweight="bold", color="black")
    ax_pacf.set_ylim(-0.3, 1.05)

fig.suptitle("Otokorelasyon Analizi — ACF & PACF (Ham Seriler)",
             fontsize=14, fontweight="bold", color="black")
plt.tight_layout()
plt.savefig("eda_acf_pacf.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()

# ── 2.5 ADF Testi (Augmented Dickey-Fuller) ──────────────────
from statsmodels.tsa.stattools import adfuller

print("=" * 62)
print("  2.6 — ADF Testi Sonuçları")
print("=" * 62)
print(f"  {'Değişken':<22} {'ADF İst.':>12}  {'p-value':>9}  {'Sonuç'}")
print(f"  {'─'*62}")

for col in COLS:
    stat, pval, *_ = adfuller(df[col].dropna(), autolag="AIC")
    flag = "✓ Durağan" if pval < 0.05 else "✗ DURAĞAN DEĞİL"
    print(f"  {col:<22} {stat:>12.4f}  {pval:>9.4f}  {flag}")

print(f"\n  NOT — Brent'in durağan olmaması beklenen bir sonuç:")
print(f"  petrol piyasası kısa vadede random walk davranışı gösterir.")
print(f"  Bu, Bölüm 6'da log-return hedefine geçişimizin gerekçesi olacak.")

print("\n✓ EDA tamamlandı. Bölüm 3 — Preprocessing'e geçebiliriz.")

# ── 3.1 Kronolojik Split ────────────────────────────────────
# Zaman serilerinde rastgele split yapılmaz.
#   Train : %70 → model bu veriden öğrenir
#   Val   : %15 → hiperparametre ayarı ve erken durdurma
#   Test  : %15 → yalnızca final değerlendirmede açılır

TRAIN_RATIO = 0.70
VAL_RATIO   = 0.15

n      = len(df)
t_end  = int(n * TRAIN_RATIO)
v_end  = int(n * (TRAIN_RATIO + VAL_RATIO))

df_train = df.iloc[:t_end].copy()
df_val   = df.iloc[t_end:v_end].copy()
df_test  = df.iloc[v_end:].copy()

train_end_date = df_train.index[-1]
val_end_date   = df_val.index[-1]

print("=" * 55)
print("  3.1 — Kronolojik Split")
print("=" * 55)
print(f"  {'Set':<8} {'Başlangıç':>12}  {'Bitiş':>12}  {'Gün':>6}  {'Oran':>6}")
print(f"  {'─'*50}")
for name, part in [("Train", df_train), ("Val", df_val), ("Test", df_test)]:
    print(f"  {name:<8} {str(part.index.min().date()):>12}  "
          f"{str(part.index.max().date()):>12}  {len(part):>6}  {len(part)/n*100:>5.1f}%")

# Görsel — split noktalarını Brent fiyatı üzerinde göster
fig, ax = plt.subplots(figsize=(16, 4))
fig.patch.set_facecolor("white")
ax.set_facecolor("white")

ax.plot(df_train.index, df_train["Brent_Petrol"], color="#1f77b4", lw=1.1,
        label=f"Train ({len(df_train)} gün)")
ax.plot(df_val.index,   df_val["Brent_Petrol"],   color="#ff7f0e", lw=1.1,
        label=f"Val ({len(df_val)} gün)")
ax.plot(df_test.index,  df_test["Brent_Petrol"],  color="#d62728", lw=1.1,
        label=f"Test ({len(df_test)} gün)")

ax.axvline(df_val.index[0],  color="#2ca02c", lw=1.5, ls="--", alpha=0.8)
ax.axvline(df_test.index[0], color="#2ca02c", lw=1.5, ls="--", alpha=0.8)

ax.set_title("Kronolojik Train / Val / Test Split", fontsize=12, fontweight="bold", color="black")
ax.set_ylabel("Brent Petrol (USD)", color="black", fontsize=9)
ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
ax.tick_params(colors="black")
for sp in ax.spines.values(): sp.set_edgecolor("#888888")
ax.grid(True, color="#dddddd", lw=0.6, alpha=0.8)
ax.legend(fontsize=9, facecolor="white", edgecolor="#cccccc", labelcolor="black")

plt.tight_layout()
plt.savefig("prep_split.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()

# ── 3.2 Wavelet Denoising ────────────────────────────────────
# Fiyat serilerindeki kısa vadeli gürültüyü temizler, trendi korur.
#
# Neden train-fit?
#   Wavelet threshold = serinin standart sapmasından hesaplanır.
#   Tüm seri üzerinde hesaplasaydık test döneminin istatistikleri
#   train'e sızardı → data leakage.
#
# Hangi değişkenlere uygulanıyor?
#   Brent, GPRD, GPRD_THREAT → gürültülü, denoising faydalı
#   OVX → zaten volatilite endeksi, dokunmuyoruz

def wavelet_fit(series: pd.Series, wavelet: str = "db4") -> dict:
    """Train verisi üzerinde threshold parametresini hesapla."""
    data  = np.nan_to_num(series.values)
    coeff = pywt.wavedec(data, wavelet, mode="per")
    sigma = (1 / 0.6745) * np.median(np.abs(coeff[-1] - np.median(coeff[-1])))
    threshold = sigma * np.sqrt(2 * np.log(len(data)))
    return {"wavelet": wavelet, "threshold": threshold}


def wavelet_transform(series: pd.Series, params: dict) -> np.ndarray:
    """Verilen threshold ile seriyi denoise et."""
    data  = np.nan_to_num(series.values)
    coeff = pywt.wavedec(data, params["wavelet"], mode="per")
    coeff[1:] = [pywt.threshold(c, value=params["threshold"], mode="hard") for c in coeff[1:]]
    return pywt.waverec(coeff, params["wavelet"], mode="per")[:len(series)]


DENOISE_COLS   = ["Brent_Petrol", "GPRD", "GPRD_THREAT"]
wavelet_params = {col: {"wavelet": "disabled", "threshold": 0.0} for col in DENOISE_COLS}


def apply_denoising(df_part: pd.DataFrame) -> pd.DataFrame:
    out = df_part.copy()
    for col in DENOISE_COLS:
        # Wavelet denoising is non-causal; keep raw values to avoid leakage.
        out[col + "_clean"] = df_part[col].values
    return out


df_train = apply_denoising(df_train)
df_val   = apply_denoising(df_val)
df_test  = apply_denoising(df_test)

print("=" * 55)
print("  3.2 — Wavelet Denoising (db4, train-fit)")
print("=" * 55)
print(f"  {'Değişken':<22}  {'Threshold':>10}  {'Noise Std':>10}")
print(f"  {'─'*46}")
for col in DENOISE_COLS:
    p     = wavelet_params[col]
    noise = (df_train[col] - df_train[col + "_clean"]).std()
    print(f"  {col:<22}  {p['threshold']:>10.4f}  {noise:>10.4f}")

# Görsel — ham vs denoised
DENOISE_COLORS = ["#1f77b4", "#ff7f0e", "#d62728"]
df_full = pd.concat([df_train, df_val, df_test])

fig, axes = plt.subplots(len(DENOISE_COLS), 1, figsize=(16, 11), sharex=True)
fig.patch.set_facecolor("white")

for i, (col, color) in enumerate(zip(DENOISE_COLS, DENOISE_COLORS)):
    ax = axes[i]
    ax.set_facecolor("white")
    raw   = df_full[col].values
    clean = df_full[col + "_clean"].values

    ax.plot(df_full.index, raw,   color="#aaaaaa", lw=0.8, alpha=0.7, label="Ham veri")
    ax.plot(df_full.index, clean, color=color,     lw=1.4, alpha=0.95, label="Wavelet Denoised")

    ax.axvline(df_val.index[0],  color="#2ca02c", lw=1.0, ls="--", alpha=0.7)
    ax.axvline(df_test.index[0], color="#2ca02c", lw=1.0, ls="--", alpha=0.7)

    noise_std = np.std(raw - clean)
    ax.text(0.01, 0.05,
            f"Threshold: {wavelet_params[col]['threshold']:.3f}  | Noise std: {noise_std:.3f}",
            transform=ax.transAxes, fontsize=8, color="black", fontfamily="monospace",
            bbox=dict(boxstyle="round,pad=0.3", facecolor="#f0f0f0", edgecolor="#cccccc"))

    ax.set_ylabel(col, color="black", fontsize=9)
    ax.tick_params(colors="black", labelsize=8)
    for sp in ax.spines.values(): sp.set_edgecolor("#888888")
    ax.grid(True, color="#dddddd", lw=0.5, alpha=0.8)
    ax.legend(fontsize=8, facecolor="white", edgecolor="#cccccc", labelcolor="black")

axes[-1].xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
axes[-1].xaxis.set_major_locator(mdates.YearLocator())
fig.suptitle("Wavelet Denoising — Ham vs Temizlenmiş Seri", fontsize=13, fontweight="bold", color="black")
plt.tight_layout()
plt.savefig("prep_wavelet.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()

# ── 3.3 Log Transform + Winsorization ───────────────────────
# OVX, GPRD, GPRD_THREAT sağa çarpık dağılım gösteriyor (EDA'da gördük).
#   1. Log transform  → dağılımı simetrikleştirir
#   2. Winsorization  → kalan aşırı değerleri kırpar (kriz spike'ları)
#
# Neden train-only?
#   Persentil sınırları train'den hesaplanır, val/test'e np.clip()
#   ile uygulanır. Test istatistikleri bu adıma karışmaz.

LOG_COLS = ["GPRD_clean", "GPRD_THREAT_clean", "OVX"]

winsor_bounds = {}
for col in LOG_COLS:
    log_vals = np.log1p(np.clip(df_train[col], 0, None))
    winsor_bounds[col] = (np.percentile(log_vals, 1.0), np.percentile(log_vals, 99.0))


def apply_log_winsor(df_part: pd.DataFrame) -> pd.DataFrame:
    out = df_part.copy()
    for col in LOG_COLS:
        log_vals = np.log1p(np.clip(df_part[col], 0, None))
        lo, hi   = winsor_bounds[col]
        fin_col  = col.replace("_clean", "_final") if "_clean" in col else col + "_final"
        out[fin_col] = np.clip(log_vals, lo, hi)
    return out


df_train = apply_log_winsor(df_train)
df_val   = apply_log_winsor(df_val)
df_test  = apply_log_winsor(df_test)

FINAL_COLS = ["GPRD_final", "GPRD_THREAT_final", "OVX_final"]

print("=" * 55)
print("  3.3 — Log Transform + Winsorization")
print("=" * 55)
print(f"  {'Değişken':<25}  {'Alt sınır':>10}  {'Üst sınır':>10}")
print(f"  {'─'*49}")
for col, fin in zip(LOG_COLS, FINAL_COLS):
    lo, hi = winsor_bounds[col]
    print(f"  {fin:<25}  {lo:>10.4f}  {hi:>10.4f}")

# Görsel — ham vs log-winsorized
fig, axes = plt.subplots(2, 3, figsize=(16, 8))
fig.patch.set_facecolor("white")

df_all = pd.concat([df_train, df_val, df_test])
PANEL_COLORS = ["#2ca02c", "#ff7f0e", "#d62728"]

for j, (raw_col, fin_col, color) in enumerate(
    zip(["OVX", "GPRD", "GPRD_THREAT"], ["OVX_final", "GPRD_final", "GPRD_THREAT_final"], PANEL_COLORS)
):
    ax_raw = axes[0, j]
    ax_raw.set_facecolor("white")
    vals_raw = df_all[raw_col].dropna().values
    ax_raw.hist(vals_raw, bins=50, color=color, alpha=0.75, edgecolor="white", linewidth=0.3)
    ax_raw.set_title(f"{raw_col} — Ham", fontsize=10, fontweight="bold", color="black")
    ax_raw.tick_params(colors="black", labelsize=7)
    for sp in ax_raw.spines.values(): sp.set_edgecolor("#888888")
    ax_raw.grid(True, axis="y", color="#dddddd", lw=0.5, alpha=0.8)
    ax_raw.text(0.02, 0.95, f"Çarpıklık: {skew(vals_raw):.2f}", transform=ax_raw.transAxes,
                fontsize=8, color="black", va="top",
                bbox=dict(boxstyle="round,pad=0.3", facecolor="#f0f0f0", edgecolor="#cccccc"))

    ax_fin = axes[1, j]
    ax_fin.set_facecolor("white")
    vals_fin = df_all[fin_col].dropna().values
    ax_fin.hist(vals_fin, bins=50, color=color, alpha=0.75, edgecolor="white", linewidth=0.3)
    ax_fin.set_title(f"{fin_col} — Log + Winsorized", fontsize=10, fontweight="bold", color="black")
    ax_fin.tick_params(colors="black", labelsize=7)
    for sp in ax_fin.spines.values(): sp.set_edgecolor("#888888")
    ax_fin.grid(True, axis="y", color="#dddddd", lw=0.5, alpha=0.8)
    ax_fin.text(0.02, 0.95, f"Çarpıklık: {skew(vals_fin):.2f}", transform=ax_fin.transAxes,
                fontsize=8, color="black", va="top",
                bbox=dict(boxstyle="round,pad=0.3", facecolor="#f0f0f0", edgecolor="#cccccc"))

fig.suptitle("Log Transform + Winsorization — Önce / Sonra", fontsize=13, fontweight="bold", color="black")
plt.tight_layout()
plt.savefig("prep_logwinsor.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()

print("\n✓ Preprocessing tamamlandı.")
print("  Bölüm 4 — Feature Engineering'e geçebiliriz.")

# ── 4.1 Tüm Seriyi Yeniden Birleştir ────────────────────────
# Preprocessing'de split ettik, feature engineering için
# tekrar birleştiriyoruz (shift/rolling geriye baktığından
# bu adım leakage üretmez — split'ten önceki dönemleri
# kullanmıyor, sadece tek bir DataFrame içinde işlem kolaylığı
# sağlıyor).

df_full = pd.concat([df_train, df_val, df_test]).sort_index()

print("=" * 55)
print("  4.1 — Mevcut Kolonlar")
print("=" * 55)
clean_cols = [c for c in df_full.columns if c not in
              ["Brent_Petrol", "OVX", "GPRD", "GPRD_THREAT"]]
for col in clean_cols:
    print(f"  {col}")

# ── 4.2 Hedef Değişken ──────────────────────────────────────
# Şimdilik yarınki Brent ham fiyatını hedefliyoruz.
#   Target_t = Brent_Petrol_{t+1}
# Not: Bölüm 6'da bu hedefin random walk tuzağına düştüğünü
# göreceğiz ve log-return'e geçeceğiz.

# Predict next-day log return instead of next-day price level.
df_full["Target"] = np.log(df_full["Brent_Petrol"].shift(-1) / df_full["Brent_Petrol"])

# ── 4.3 Temel Lag ve EMA Feature'ları ───────────────────────
# Lag: t anında dünün, önceki günlerin bilgisi.
# EMA: üstel ağırlıklı ortalama — yakın geçmişe daha fazla ağırlık.

LAG_MAX   = 5
EMA_SPANS = [5, 10, 20]

BASE_SERIES = {
    "Brent_clean"  : df_full["Brent_Petrol_clean"],
    "GPRD"         : df_full["GPRD_final"],
    "GPRD_THREAT"  : df_full["GPRD_THREAT_final"],
    "OVX"          : df_full["OVX_final"],
}

for name, series in BASE_SERIES.items():
    for lag in range(1, LAG_MAX + 1):
        df_full[f"{name}_lag{lag}"] = series.shift(lag)
    for span in EMA_SPANS:
        df_full[f"{name}_ema{span}"] = series.ewm(span=span, adjust=False).mean().shift(1)

print("=" * 55)
print("  4.3 — Temel Lag + EMA Feature'ları")
print("=" * 55)
basic_feats = [c for c in df_full.columns
               if any(c.startswith(n) and ("lag" in c or "ema" in c) for n in BASE_SERIES)]
print(f"  Üretilen feature sayısı: {len(basic_feats)}")

# ── 4.4 Volatilite Feature'ları ─────────────────────────────
# Realized volatility: geçmiş fiyat hareketlerinin std'si.

brent_ret = np.log(df_full["Brent_Petrol"] / df_full["Brent_Petrol"].shift(1))
df_full["brent_vol5"]  = brent_ret.rolling(5).std().shift(1)
df_full["brent_vol20"] = brent_ret.rolling(20).std().shift(1)
df_full["vol_ratio"]   = df_full["brent_vol5"] / (df_full["brent_vol20"] + 1e-9)

print("  4.4 — Volatilite Feature'ları: brent_vol5, brent_vol20, vol_ratio ✓")

# ── 4.5 OVX Türev Feature'ları ──────────────────────────────
# OVX'in seviyesi değil, tarihsel norma göre konumu daha
# taşınabilir bir sinyal taşır.

ROLL_WIN = 60

ovx_raw = df_full["OVX_final"]
ovx_roll_mean = ovx_raw.rolling(ROLL_WIN).mean().shift(1)
ovx_roll_std  = ovx_raw.rolling(ROLL_WIN).std().shift(1)
df_full["ovx_zscore"] = (ovx_raw.shift(1) - ovx_roll_mean) / (ovx_roll_std + 1e-9)
df_full["ovx_spike"]  = (df_full["ovx_zscore"] > 2.0).astype(int)

ovx_ema20 = ovx_raw.ewm(span=20, adjust=False).mean().shift(1)
ovx_ema60 = ovx_raw.ewm(span=60, adjust=False).mean().shift(1)
df_full["ovx_high_regime"] = (ovx_ema20 > ovx_ema60).astype(int)
df_full["ovx_mean_revert"] = df_full["ovx_zscore"] * (-(ovx_raw.diff().shift(1)))

print("  4.5 — OVX Türev Feature'ları: ovx_zscore, ovx_spike,")
print("        ovx_high_regime, ovx_mean_revert ✓")

# ── 4.6 GPR Türev Feature'ları ──────────────────────────────

gprd_raw   = df_full["GPRD_final"]
gprd_t_raw = df_full["GPRD_THREAT_final"]

df_full["gpr_threat_ratio"] = gprd_t_raw.shift(1) / (gprd_raw.shift(1) + 1e-9)

gprd_roll_mean = gprd_raw.rolling(ROLL_WIN).mean().shift(1)
gprd_roll_std  = gprd_raw.rolling(ROLL_WIN).std().shift(1)
df_full["gprd_zscore"] = (gprd_raw.shift(1) - gprd_roll_mean) / (gprd_roll_std + 1e-9)
df_full["gprd_spike"]  = (df_full["gprd_zscore"] > 2.0).astype(int)

gprd_ema5  = gprd_raw.ewm(span=5,  adjust=False).mean().shift(1)
gprd_ema20 = gprd_raw.ewm(span=20, adjust=False).mean().shift(1)
df_full["gprd_momentum"] = gprd_ema5 - gprd_ema20

gprd_t_mean = gprd_t_raw.rolling(ROLL_WIN).mean().shift(1)
gprd_t_std  = gprd_t_raw.rolling(ROLL_WIN).std().shift(1)
df_full["gprd_threat_zscore"] = (gprd_t_raw.shift(1) - gprd_t_mean) / (gprd_t_std + 1e-9)

print("  4.6 — GPR Türev Feature'ları: gpr_threat_ratio, gprd_zscore,")
print("        gprd_spike, gprd_momentum, gprd_threat_zscore ✓")

# ── 4.7 Etkileşim (Cross) Feature'ları ──────────────────────
# OVX ve GPR birlikte yükseldiğinde fiyat üzerindeki etki tek
# başlarının toplamından daha güçlü olabilir.

df_full["ovx_gprd_interact"]        = df_full["OVX_final"].shift(1) * df_full["GPRD_final"].shift(1)
df_full["ovx_gprd_threat_interact"] = df_full["OVX_final"].shift(1) * df_full["GPRD_THREAT_final"].shift(1)
df_full["regime_gprd_interact"]     = df_full["ovx_high_regime"] * df_full["GPRD_final"].shift(1)
df_full["spike_ovx_interact"]       = df_full["gprd_spike"] * df_full["OVX_final"].shift(1)

print("  4.7 — Etkileşim Feature'ları: ovx_gprd_interact,")
print("        ovx_gprd_threat_interact, regime_gprd_interact,")
print("        spike_ovx_interact ✓")

# ── 4.8 Takvim Feature'ları ─────────────────────────────────

df_full["day_of_week"]    = df_full.index.dayofweek
df_full["month"]          = df_full.index.month
df_full["is_month_end"]   = df_full.index.is_month_end.astype(int)
df_full["is_month_start"] = df_full.index.is_month_start.astype(int)

print("  4.8 — Takvim Feature'ları: day_of_week, month,")
print("        is_month_end, is_month_start ✓")

# ── 4.9 NaN Temizliği ve Yeniden Split ──────────────────────

DROP_COLS = ["Brent_Petrol", "OVX", "GPRD", "GPRD_THREAT",
             "Brent_Petrol_clean", "GPRD_clean", "GPRD_THREAT_clean"]

df_full.dropna(inplace=True)

FEATURES = [c for c in df_full.columns
            if c not in DROP_COLS + ["Target", "GPRD_final", "GPRD_THREAT_final", "OVX_final"]]

train = df_full.loc[:train_end_date]
val   = df_full.loc[(df_full.index > train_end_date) & (df_full.index <= val_end_date)]
test  = df_full.loc[df_full.index > val_end_date]

X_train = train[FEATURES]; y_train = train["Target"]
X_val   = val[FEATURES];   y_val   = val["Target"]
X_test  = test[FEATURES];  y_test  = test["Target"]

print("=" * 55)
print("  4.9 — Özet")
print("=" * 55)
print(f"  Toplam feature : {len(FEATURES)}")
print(f"  Train          : {X_train.shape}")
print(f"  Val            : {X_val.shape}")
print(f"  Test           : {X_test.shape}")

# ── 4.10 Feature Korelasyon Isı Haritası ────────────────────
# Feature'lar arası yüksek korelasyon LSTM için önemli olabilir.

corr_matrix = X_train.corr()

fig, ax = plt.subplots(figsize=(18, 15))
fig.patch.set_facecolor("white")
ax.set_facecolor("white")

im = ax.imshow(corr_matrix.values, cmap="RdBu_r", vmin=-1, vmax=1, aspect="auto")
ax.set_xticks(range(len(FEATURES))); ax.set_yticks(range(len(FEATURES)))
ax.set_xticklabels(FEATURES, rotation=90, ha="right", color="black", fontsize=6)
ax.set_yticklabels(FEATURES, color="black", fontsize=6)

cb = plt.colorbar(im, ax=ax, fraction=0.03, pad=0.02)
cb.ax.tick_params(colors="black", labelsize=8)
cb.set_label("Korelasyon", color="black", fontsize=9)

ax.set_title("Feature Korelasyon Matrisi (Train Seti)", fontsize=13,
             fontweight="bold", color="black", pad=12)
for sp in ax.spines.values(): sp.set_edgecolor("#888888")

plt.tight_layout()
plt.savefig("fe_correlation.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()

# Yüksek korelasyonlu çiftleri raporla
print("\n  |r| > 0.90 olan feature çiftleri:")
high_corr_pairs = []
for i in range(len(FEATURES)):
    for j in range(i+1, len(FEATURES)):
        r = corr_matrix.iloc[i, j]
        if abs(r) > 0.90:
            high_corr_pairs.append((FEATURES[i], FEATURES[j], r))

if high_corr_pairs:
    for f1, f2, r in sorted(high_corr_pairs, key=lambda x: abs(x[2]), reverse=True):
        print(f"  {f1:<30}  ↔  {f2:<30}  r={r:.3f}")
else:
    print("  Yok — multicollinearity riski düşük ✓")

print("\n✓ Feature Engineering tamamlandı.")
print("  Bölüm 5 — XGBoost'a geçebiliriz.")

# ── 4.11 Feature Winsorization + Scaling ─────────────────────
# Bölüm 3'teki winsorization yalnızca ham OVX/GPRD/GPRD_THREAT
# seviyelerine uygulanmıştı. Bölüm 4'te türetilen feature'lar
# (lag, EMA, z-score, etkileşim terimleri) henüz hiç işlenmedi.
#
# İki ayrı strateji:
#   Sürekli feature'lar → [1, 99] persentil winsorization → MinMaxScaler
#   Binary feature'lar  → winsorize etme, scale etme (zaten 0/1)


from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

BINARY_FEATS = ["ovx_spike", "ovx_high_regime", "gprd_spike",
                "is_month_end", "is_month_start"]

CONTINUOUS_FEATS = [f for f in FEATURES if f not in BINARY_FEATS]

# ── Winsorization (train-only) ──────────────────────────────
winsor_bounds = {}
for col in CONTINUOUS_FEATS:
    lo = np.percentile(X_train[col], 1.0)
    hi = np.percentile(X_train[col], 99.0)
    winsor_bounds[col] = (lo, hi)

def apply_winsor(df_part):
    out = df_part.copy()
    for col in CONTINUOUS_FEATS:
        out[col] = np.clip(out[col], *winsor_bounds[col])
    return out

X_train_w = apply_winsor(X_train)
X_val_w   = apply_winsor(X_val)
X_test_w  = apply_winsor(X_test)

# ── Scaling (train-only fit) ────────────────────────────────
scaler = MinMaxScaler()
scaler.fit(X_train_w[CONTINUOUS_FEATS])

def scale_df(df_part):
    out = df_part.copy()
    out[CONTINUOUS_FEATS] = scaler.transform(df_part[CONTINUOUS_FEATS])
    return out

X_train_s = scale_df(X_train_w)
X_val_s   = scale_df(X_val_w)
X_test_s  = scale_df(X_test_w)

y_train_arr = y_train.values
y_val_arr   = y_val.values
y_test_arr  = y_test.values

import joblib
joblib.dump(scaler, "scaler_features.pkl")

print("=" * 55)
print("  5.1 — Feature Winsorization + Scaling")
print("=" * 55)
print(f"  Sürekli feature (winsor + scale) : {len(CONTINUOUS_FEATS)}")
print(f"  Binary feature  (ham bırakıldı)  : {len(BINARY_FEATS)}")
print(f"  X_train_s : {X_train_s.shape}")
print(f"  X_val_s   : {X_val_s.shape}")
print(f"  X_test_s  : {X_test_s.shape}")
